### ISSUE TITLE
Biogeme is not found

### ISSUE THREAD

**Issue by MerlevB** [SEN1221TUD/Q2_2023#2]
Hi!

I have uploaded  all the required packages in the requirements.txt (including Biogeme). But already with the first import of the Biogeme package, it says there is no module named Biogeme. How can I fix this?

Thanks in advance,
Merle 

<img width="1437" alt="Scherm­afbeelding 2023-11-19 om 22 41 46" src="https://github.com/SEN1221TUD/Q2_2023/assets/151473072/66a684d2-8167-45f0-8076-86c6ce2d806e">
<img width="1437" alt="Scherm­afbeelding 2023-11-19 om 22 41 52" src="https://github.com/SEN1221TUD/Q2_2023/assets/151473072/b5f9652c-3560-44bc-980a-9ace3ffad8d4">

**Comment by gnova3** [comment]
Hello Merle, 

We are working on providing detailed instructions on how to use Anaconda and Python environments and hope to have it ready tomorrow.

Gabriel
